### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by stephenyeargin** [robhurring/hubot-redmine#13]
The new way to handle Hubot scripts is to publish them to http://npmjs.org for easy inclusion via the `package.json` + `external-scripts.json` declaration. In an ideal world, this would be published there and then made part of the @hubot-scripts organization.

Reference: https://github.com/github/hubot-scripts/blob/master/CONTRIBUTING.md

**Comment by abeger** [comment]
+1 to this

**Comment by stephenyeargin** [comment]
I published it: https://www.npmjs.com/package/hubot-redmine

@robhurring - I'm happy to move it to you if you let me know what your npmjs.com username might be. If you're not as familiar with the platform, I've got a dozen or so packages I help maintain if I can be a collaborator on this repo (needed to bump the versions in `package.json`)

**Comment by robhurring** [comment]
@stephenyeargin thats fine, I haven't paid much attention to this repo lately. I've added you as a collaborator here :smile:
