### ISSUE TITLE
Namespace the commands for this plugin

### ISSUE THREAD

**Issue by stephenyeargin** [robhurring/hubot-redmine#21]
## Synopsis

This plugin should play nice with other plugins, with actions more explicit. This means appending `redmine` or `rm` in front of commands so that the end-user isn't confused.
## Scenario

Let's say you work for a company that uses many different services. Among them: Redmine, Zendesk, GitHub, Trello and others. You want to integrate as much as you can with Hubot, because it makes for a better way of working. All good so far.

But this plugin has a slight drawback.

```
Sue> Hey @rob, can you send that issue you were working on back to me when you're done?
Rob> No problem!
Rob> hubot assign 2514 to sue
Hubot> Assigned #2514 to Sue.
Hubot> Could not find incident #2514!
```

That second message is from a something else on Hubot that doesn't have name-spacing enabled. You can't use these two side by side without potentially issuing a command it doesn't understand or one that was not intended.
## The Fix

Appending either `redmine`, `rm` or some other handle in front of the commands would make a collision less likely. Really, all plugins should follow this guideline, but not all do.

We could phase it in to accept those commands (and update the docs) or make a hard cut-over where folks would have to adjust whenever they have a version bump. I do not think it would be very disruptive. This would also allow users to leverage the `hubot-help` commands easier to find the ones related to Redmine.

**Comment by xurizaemon** [comment]
Possible to make it configurable as well via a new environment variable which is checked when setting the listeners.
